baseurl = "https://hype.testlio.com/"
languageCode = "en-us"
title = "#testliohype"
theme = "casper"

[params]
    hideHUGOSupport = true
    cover = "images/cover.png"
    ogCover = "images/cover-og.png"
    description = "Engineering at Testlio"

    googleAnalyticsUserID = "UA-36245654-1"
    logo = "images/icon.png"


    githubName = "testlio"
    twitterName = "testlio"
    facebookName = "testlio"
    instagramName = "testlio"

    customHeaderPartial = "header_end.html"

[blackfriday]
    hrefTargetBlank = true
